services:
  api:
    image: financa-api:staging
    container_name: financa-api
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}

  db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=${DB_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  oracle_data: