name: Deploy DEV

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy-dev:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'develop'

    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build e Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}

      - name: Deploy
        run: curl -X POST "${{ secrets.DEPLOY_HOOK }}"